config/routes.rb
Rails.application.routes.draw do
  resources :espacios
  resources :tipo_viviendas
  resources :viviendas
  get 'admin/create_user'
  get 'admin/edit_user'

  root 'viviendas#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

    # Permisos del admin
    resources :admin, only: [:index, :new, :create, :update]
    # Ruta para crear usuarios
    post 'admin/create', to: 'admin#create', as: 'admin_create'

end

app/models/tipo_vivienda.rb
class TipoVivienda < ApplicationRecord
  has_many :viviendas, dependent: :destroy
end

app/controllers/tipo_viviendas_controller.rb
class TipoViviendasController < ApplicationController
  before_action :set_tipo_vivienda, only: %i[ show edit update destroy ]

  # GET /tipo_viviendas or /tipo_viviendas.json
  def index
    @tipo_viviendas = TipoVivienda.all
  end

  # GET /tipo_viviendas/1 or /tipo_viviendas/1.json
  def show
  end

  # GET /tipo_viviendas/new
  def new
    @tipo_vivienda = TipoVivienda.new
  end

  # GET /tipo_viviendas/1/edit
  def edit
  end

  # POST /tipo_viviendas or /tipo_viviendas.json
  def create
    @tipo_vivienda = TipoVivienda.new(tipo_vivienda_params)

    respond_to do |format|
      if @tipo_vivienda.save
        format.html { redirect_to tipo_vivienda_url(@tipo_vivienda), notice: "Tipo vivienda was successfully created." }
        format.json { render :show, status: :created, location: @tipo_vivienda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_vivienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_viviendas/1 or /tipo_viviendas/1.json
  def update
    respond_to do |format|
      if @tipo_vivienda.update(tipo_vivienda_params)
        format.html { redirect_to tipo_vivienda_url(@tipo_vivienda), notice: "Tipo vivienda was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_vivienda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_vivienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_viviendas/1 or /tipo_viviendas/1.json
  def destroy
    @tipo_vivienda.destroy

    respond_to do |format|
      format.html { redirect_to tipo_viviendas_url, notice: "Tipo vivienda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_vivienda
      @tipo_vivienda = TipoVivienda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_vivienda_params
      params.require(:tipo_vivienda).permit(:nombre)
    end
end

app/helpers/tipo_viviendas_helper.rb
module TipoViviendasHelper
end

app/views/tipo_viviendas/_form.html.erb
<%= form_with(model: tipo_vivienda) do |form| %>
  <% if tipo_vivienda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tipo_vivienda.errors.count, "error") %> prohibited this tipo_vivienda from being saved:</h2>

      <ul>
        <% tipo_vivienda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_viviendas/_tipo_vivienda.html.erb
<div id="<%= dom_id tipo_vivienda %>">
  <p>
    <strong>Nombre:</strong>
    <%= tipo_vivienda.nombre %>
  </p>

</div>

app/views/tipo_viviendas/edit.html.erb
<h1>Editing tipo vivienda</h1>

<%= render "form", tipo_vivienda: @tipo_vivienda %>

<br>

<div>
  <%= link_to "Show this tipo vivienda", @tipo_vivienda %> |
  <%= link_to "Back to tipo viviendas", tipo_viviendas_path %>
</div>

app/views/tipo_viviendas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tipo viviendas</h1>

<div id="tipo_viviendas">
  <% @tipo_viviendas.each do |tipo_vivienda| %>
    <%= render tipo_vivienda %>
    <p>
      <%= link_to "Show this tipo vivienda", tipo_vivienda %>
    </p>
  <% end %>
</div>

<%= link_to "New tipo vivienda", new_tipo_vivienda_path %>

app/views/tipo_viviendas/new.html.erb
<h1>New tipo vivienda</h1>

<%= render "form", tipo_vivienda: @tipo_vivienda %>

<br>

<div>
  <%= link_to "Back to tipo viviendas", tipo_viviendas_path %>
</div>

app/views/tipo_viviendas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tipo_vivienda %>

<div>
  <%= link_to "Edit this tipo vivienda", edit_tipo_vivienda_path(@tipo_vivienda) %> |
  <%= link_to "Back to tipo viviendas", tipo_viviendas_path %>

  <%= button_to "Destroy this tipo vivienda", @tipo_vivienda, method: :delete %>
</div>