config/routes.rb
Rails.application.routes.draw do
  resources :espacios
  resources :tipo_viviendas
  resources :viviendas
  get 'admin/create_user'
  get 'admin/edit_user'

  root 'viviendas#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

    # Permisos del admin
    resources :admin, only: [:index, :new, :create, :update]
    # Ruta para crear usuarios
    post 'admin/create', to: 'admin#create', as: 'admin_create'

end

app/views/admin/create_user.html.erb
<%= form_with(model: @user, url: admin_create_path, method: :post) do |f| %>
  <%= f.fields_for :user do |user_fields| %>
    <div class="container">
      <div class="row justify-content-center mt-5">
        <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="card shadow">
            <div class="card-title text-center border-bottom">
              <h2 class="p-3">Create new user</h2>
            </div>
            <div class="card-body">
              <form>
                <div class="mb-4">
                  <%= user_fields.label :username %><br />
                  <%= user_fields.text_field :username, autofocus: true, autocomplete: "username"  %>
                </div>
                <div class="mb-4">
                  <%= user_fields.label :email %><br />
                  <%= user_fields.email_field :email, autocomplete: "email"  %>
                </div>
                <div class="mb-4">
                  <%= user_fields.label :role %><br />
                  <%= user_fields.select :role, User.roles.keys.map { |w| [w.humanize, w] }, include_blank: "Select a role" %>
                </div>
                <div class="mb-4">
                  <%= user_fields.label :password %>
                  <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br />
                  <%= user_fields.password_field :password, autocomplete: "new-password" %>
                </div>
                <div class="mb-4">
                  <%= user_fields.label :password_confirmation %><br />
                  <%= user_fields.password_field :password_confirmation, autocomplete: "new-password" %>
                </div>
                <% end %>
                <div>
                  <%= f.submit "Create user", class:"btn btn-success" %>
                </div>
              <% end %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<br >

app/views/admin/edit_user.html.erb
<!--Listar todos los user y poder editar sus campos-->

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8 col-md-6 col-sm-6">
      <div class="card shadow">
        <div class="card-title text-center border-bottom">
          <h2 class="p-3">Edit user</h2>
          </div>
          <div class="card-body">
            <form>
              <% @users.each do |user| %>
                <%= form_for(user, url: admin_path(user), remote: true, method: :patch) do |f| %>
                  <p><%= f.text_field :email %> - <%= f.text_field :username %> - <%= f.select(:role, User.roles.keys.map { |w| [w.humanize, w] }) %> - <%= f.submit "Update", class: "btn btn-success" %></p>
                <% end %>
              <% end %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<br>