config/routes.rb
Rails.application.routes.draw do
  resources :espacios
  resources :tipo_viviendas
  resources :viviendas
  get 'admin/create_user'
  get 'admin/edit_user'

  root 'viviendas#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

    # Permisos del admin
    resources :admin, only: [:index, :new, :create, :update]
    # Ruta para crear usuarios
    post 'admin/create', to: 'admin#create', as: 'admin_create'

end

app/models/vivienda.rb
class Vivienda < ApplicationRecord
  belongs_to :user
  belongs_to :tipo_vivienda
    has_many :viviendas_espacios, dependent: :destroy
  has_many :espacios, through: :viviendas_espacios
end

app/controllers/viviendas_controller.rb
class ViviendasController < ApplicationController
  before_action :set_vivienda, only: %i[ show edit update destroy ]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /viviendas or /viviendas.json
  def index
    @viviendas = Vivienda.all
  end

  # GET /viviendas/1 or /viviendas/1.json
  def show
  end

  # GET /viviendas/new
  def new
    @vivienda = Vivienda.new
  end

  # GET /viviendas/1/edit
  def edit
  end

  # POST /viviendas or /viviendas.json
  def create
    @vivienda = current_user.viviendas.build(vivienda_params)

    respond_to do |format|
      if @vivienda.save
        format.html { redirect_to vivienda_url(@vivienda), notice: "Vivienda was successfully created." }
        format.json { render :show, status: :created, location: @vivienda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vivienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /viviendas/1 or /viviendas/1.json
  def update
    respond_to do |format|
      if @vivienda.update(vivienda_params)
        format.html { redirect_to vivienda_url(@vivienda), notice: "Vivienda was successfully updated." }
        format.json { render :show, status: :ok, location: @vivienda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vivienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viviendas/1 or /viviendas/1.json
  def destroy
    @vivienda.destroy

    respond_to do |format|
      format.html { redirect_to viviendas_url, notice: "Vivienda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vivienda
      @vivienda = Vivienda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vivienda_params
      params.require(:vivienda).permit(:user_id, :superficie, :direccion, :tipo_vivienda_id, espacio_ids: [])
    end

    def authorize_user!
      # Solo permite que el administrador o el creador de la vivienda realicen acciones de edición y eliminación
      unless current_user.admin? || current_user == @vivienda.user
        redirect_to root_path, alert: "No tienes permisos para realizar esta acción."
      end
    end

end

app/helpers/viviendas_helper.rb
module ViviendasHelper
end

app/views/viviendas/_form.html.erb
<%= form_with(model: vivienda) do |form| %>
  <% if vivienda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vivienda.errors.count, "error") %> prohibited this vivienda from being saved:</h2>

      <ul>
        <% vivienda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div>
    <%= form.label :superficie, style: "display: block" %>
    <%= form.number_field :superficie %>
  </div>

  <div>
    <%= form.label :direccion, style: "display: block" %>
    <%= form.text_field :direccion %>
  </div>

  <div>
    <%= form.label :tipo_vivienda_id, style: "display: block" %>
    <%= form.collection_select :tipo_vivienda_id, TipoVivienda.all, :id, :nombre %>
  </div>

  <div>
    <%= form.label :espacios, style: "display: block" %>
    <% Espacio.all.each do |espacio| %>
      <label>
        <%= check_box_tag "vivienda[espacio_ids][]", espacio.id, @vivienda.espacios.include?(espacio) %>
        <%= espacio.nombre %>
      </label>
    <% end %>
  </div>

  <div>
    <%= form.submit "Guardar" %>
  </div>
<% end %>

app/views/viviendas/_vivienda.html.erb
<div id="<%= dom_id vivienda %>">
  <p>
    <strong>User:</strong>
    <%= vivienda.user.username %>
  </p>

  <p>
    <strong>Superficie:</strong>
    <%= vivienda.superficie %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= vivienda.direccion %>
  </p>

  <p>
    <strong>Tipo de Vivienda:</strong>
    <%= vivienda.tipo_vivienda.nombre %>
  </p>

<p>
  <strong>Espacios:</strong>
  <%= vivienda.espacios.map(&:nombre).join(', ') %>
</p>

</div>

app/views/viviendas/edit.html.erb
<h1>Editing vivienda</h1>

<%= render "form", vivienda: @vivienda %>

<br>

<div>
  <%= link_to "Show this vivienda", @vivienda %> |
  <%= link_to "Back to viviendas", viviendas_path %>
</div>

app/views/viviendas/index.html.erb
 <div class="container">
  <h1>Viviendas</h1>
  <div id="viviendas">
    <% @viviendas.each do |vivienda| %>
      <%= render vivienda %>
      <p>
        <%= link_to "Show this vivienda", vivienda %>
      </p>
    <% end %>
  </div>
  <!--Muestra la opción crear solo si el user está logeado-->
  <% if user_signed_in? && current_user.user? || current_user.admin?  %>
    <%= link_to 'New vivienda', new_vivienda_path %>
  <% end %>
 </div>

app/views/viviendas/new.html.erb
<h1>New vivienda</h1>

<%= render "form", vivienda: @vivienda %>

<br>

<div>
  <%= link_to "Back to viviendas", viviendas_path %>
</div>

app/views/viviendas/show.html.erb
<div class="container">
  <%= render @vivienda %>

    <%= link_to "Back to viviendas", viviendas_path %>

    <% if user_signed_in? && current_user.user? || current_user.admin?  %> |
      <%= link_to "Edit this vivienda", edit_vivienda_path(@vivienda) %>
      <%= button_to "Destroy this vivienda", @vivienda, method: :delete %>
    <% end %>

</div>