config/routes.rb
Rails.application.routes.draw do
  resources :espacios
  resources :tipo_viviendas
  resources :viviendas
  get 'admin/create_user'
  get 'admin/edit_user'

  root 'viviendas#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

    # Permisos del admin
    resources :admin, only: [:index, :new, :create, :update]
    # Ruta para crear usuarios
    post 'admin/create', to: 'admin#create', as: 'admin_create'

end

app/models/espacio.rb
class Espacio < ApplicationRecord
  has_many :viviendas_espacios
  has_many :viviendas, through: :viviendas_espacios
end

app/controllers/espacios_controller.rb
class EspaciosController < ApplicationController
  before_action :set_espacio, only: %i[ show edit update destroy ]

  # GET /espacios or /espacios.json
  def index
    @espacios = Espacio.all
  end

  # GET /espacios/1 or /espacios/1.json
  def show
  end

  # GET /espacios/new
  def new
    @espacio = Espacio.new
  end

  # GET /espacios/1/edit
  def edit
  end

  # POST /espacios or /espacios.json
  def create
    @espacio = Espacio.new(espacio_params)

    respond_to do |format|
      if @espacio.save
        format.html { redirect_to espacio_url(@espacio), notice: "Espacio was successfully created." }
        format.json { render :show, status: :created, location: @espacio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @espacio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espacios/1 or /espacios/1.json
  def update
    respond_to do |format|
      if @espacio.update(espacio_params)
        format.html { redirect_to espacio_url(@espacio), notice: "Espacio was successfully updated." }
        format.json { render :show, status: :ok, location: @espacio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @espacio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espacios/1 or /espacios/1.json
  def destroy
    @espacio.destroy

    respond_to do |format|
      format.html { redirect_to espacios_url, notice: "Espacio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espacio
      @espacio = Espacio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def espacio_params
      params.require(:espacio).permit(:nombre)
    end
end

app/helpers/espacios_helper.rb
module EspaciosHelper
end

app/views/espacios/_espacio.html.erb
<div id="<%= dom_id espacio %>">
  <p>
    <strong>Nombre:</strong>
    <%= espacio.nombre %>
  </p>

</div>

app/views/espacios/_form.html.erb
<%= form_with(model: espacio) do |form| %>
  <% if espacio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(espacio.errors.count, "error") %> prohibited this espacio from being saved:</h2>

      <ul>
        <% espacio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/espacios/edit.html.erb
<h1>Editing espacio</h1>

<%= render "form", espacio: @espacio %>

<br>

<div>
  <%= link_to "Show this espacio", @espacio %> |
  <%= link_to "Back to espacios", espacios_path %>
</div>

app/views/espacios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Espacios</h1>

<div id="espacios">
  <% @espacios.each do |espacio| %>
    <%= render espacio %>
    <p>
      <%= link_to "Show this espacio", espacio %>
    </p>
  <% end %>
</div>

<%= link_to "New espacio", new_espacio_path %>

app/views/espacios/new.html.erb
<h1>New espacio</h1>

<%= render "form", espacio: @espacio %>

<br>

<div>
  <%= link_to "Back to espacios", espacios_path %>
</div>

app/views/espacios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @espacio %>

<div>
  <%= link_to "Edit this espacio", edit_espacio_path(@espacio) %> |
  <%= link_to "Back to espacios", espacios_path %>

  <%= button_to "Destroy this espacio", @espacio, method: :delete %>
</div>